# Generated by Django 4.2.6 on 2024-04-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
