# Generated by Django 4.2.6 on 2024-05-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_factura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='direccion',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='numero',
        ),
    ]
