# Generated by Django 4.2.6 on 2024-05-03 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_rename_direccion_factura_url_remove_factura_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
