# Generated by Django 4.2.6 on 2024-05-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_factura_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='deuda',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='registro',
            name='tipo_pago',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='tipo_venta',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
