# Generated by Django 4.2.6 on 2024-05-24 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_deudas_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='registro',
        ),
    ]
