# Generated by Django 4.2.6 on 2024-05-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_remove_deudas_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='adelanto',
        ),
        migrations.AddField(
            model_name='registro',
            name='adelanto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
