# Generated by Django 4.2.6 on 2024-05-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_remove_deudas_adelanto_registro_adelanto'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas',
            name='estado',
            field=models.CharField(default='pendiente', max_length=10),
        ),
    ]
