# Generated by Django 4.2.6 on 2024-05-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_deudas_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='estado',
        ),
    ]
