# Generated by Django 4.2.6 on 2024-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_remove_deudas_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(default='pendiente', max_length=10),
        ),
    ]
