# Generated by Django 4.2.6 on 2024-06-04 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_pago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas',
            name='estado',
            field=models.CharField(default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='deudas',
            name='registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.registro'),
        ),
    ]
