# Generated by Django 4.2.6 on 2024-06-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_deudas_estado_deudas_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('direccionEnvio', models.CharField(max_length=255)),
                ('productos', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotalD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentajeDescuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipoPago', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
                ('numeroCheque', models.CharField(blank=True, max_length=50, null=True)),
                ('numeroFactura', models.CharField(max_length=50)),
                ('combinados', models.TextField()),
                ('tipoVenta', models.CharField(max_length=50)),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuarioVendedor', models.CharField(max_length=100)),
            ],
        ),
    ]
