# Generated by Django 4.2.6 on 2024-06-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_facturacredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacredito',
            name='abono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='descuento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='iva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='peso',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='porcentaje',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='porcentajeDescuento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='saldo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='subtotal',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='subtotalD',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facturacredito',
            name='total',
            field=models.CharField(max_length=20),
        ),
    ]
