# Generated by Django 4.2.6 on 2024-06-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_alter_facturacredito_abono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacredito',
            name='combinados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
