# Generated by Django 4.2.6 on 2024-06-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_alter_facturacredito_combinados'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacredito',
            name='deuda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.deudas'),
        ),
    ]
