# Generated by Django 4.2.6 on 2024-07-09 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0007_alter_caja_cajero'),
        ('ventas', '0020_servicio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.caja'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='abono',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
