# Generated by Django 4.2.6 on 2024-08-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_remove_servicio_abono_pagoserviciocombinado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='abonado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
