# Generated by Django 4.2.6 on 2024-08-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0024_servicio_abonado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoservicio',
            name='combinados',
        ),
        migrations.AddField(
            model_name='pagoservicio',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagoservicio',
            name='numeroTransferencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
