# Generated by Django 4.2.6 on 2024-08-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0025_remove_pagoservicio_combinados_pagoservicio_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='numero_reparacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
