# Generated by Django 4.2.6 on 2024-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0029_rename_descuento_servicio_costo_sin_descuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagoserviciocombinado',
            old_name='valorTarjeta',
            new_name='valorTarjetaCredito',
        ),
        migrations.AddField(
            model_name='pagoserviciocombinado',
            name='valorTarjetaDebito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
