# Generated by Django 4.2.6 on 2024-09-04 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0030_rename_valortarjeta_pagoserviciocombinado_valortarjetacredito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoRegistroCombinado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorEfectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorTarjetaCredito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorTarjetaDebito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorCheque', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorTransferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.registro')),
            ],
        ),
        migrations.CreateModel(
            name='PagoPendienteCombinado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorEfectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorTarjetaCredito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorTarjetaDebito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorCheque', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorTransferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pago')),
            ],
        ),
    ]
