# Generated by Django 4.2.6 on 2024-09-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0031_pagoregistrocombinado_pagopendientecombinado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='numeroCheque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='numeroTransferencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipoPago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
