# Generated by Django 4.2.6 on 2025-02-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0033_equipo_descripcionequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='deuda',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
