# Generated by Django 4.2.6 on 2025-02-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0034_alter_registro_deuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='estado',
            field=models.CharField(default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(default='pendiente', max_length=15),
        ),
    ]
