# Generated by Django 4.2.6 on 2025-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0035_alter_deudas_estado_alter_pago_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcionequipo',
            name='problema',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
