# Generated by Django 4.2.6 on 2025-07-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0036_alter_descripcionequipo_problema'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionequipo',
            name='solucion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
