# Generated by Django 4.2.6 on 2023-11-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_categoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='subCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='subCategorias')),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.categoria')),
            ],
        ),
    ]
