# Generated by Django 4.2.6 on 2023-11-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_carrusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='imagen',
            field=models.ImageField(upload_to='carrusel'),
        ),
    ]
