# Generated by Django 4.2.6 on 2024-02-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_alter_adicionalusuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionalusuario',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
