# Generated by Django 4.2.6 on 2024-02-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_adicionalusuario_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionalusuario',
            name='celular',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
