# Generated by Django 4.2.6 on 2024-03-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_adicionalusuario_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionalusuario',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
