# Generated by Django 4.2.6 on 2024-04-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_adicionalusuario_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionalusuario',
            name='token',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
