# Generated by Django 4.2.6 on 2024-05-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0016_alter_adicionalusuario_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionalusuario',
            name='deuda',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
