# Generated by Django 4.2.6 on 2024-07-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0019_alter_descuentoservicio_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentoservicio',
            name='porcentaje',
            field=models.CharField(max_length=3),
        ),
    ]
