# Generated by Django 4.2.6 on 2025-06-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0022_alter_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionalusuario',
            name='cedula',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
