# Generated by Django 4.2.6 on 2023-11-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_producto_precio_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Este campo no es necesario.', max_digits=10, null=True),
        ),
    ]
