# Generated by Django 4.2.6 on 2023-11-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_producto_precio_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(help_text='Toda la descripción y características del producto.', null=True),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='detalle',
            field=models.CharField(help_text='Detalles precisos que van en la presentación del producto.', max_length=600, null=True),
        ),
    ]
