# Generated by Django 4.2.6 on 2023-11-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_producto_descripcion_alter_imagenproducto_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='modelo',
        ),
    ]
