# Generated by Django 4.2.6 on 2023-11-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_producto_calidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='codigo_articulo',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_referencial',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
