# Generated by Django 4.2.6 on 2023-11-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_remove_producto_codigo_articulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='productos.producto'),
        ),
    ]
