# Generated by Django 4.2.6 on 2023-11-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_alter_colorstock_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstock',
            name='codigo_referencial',
            field=models.CharField(default='sn', max_length=255),
        ),
    ]
