# Generated by Django 4.2.6 on 2023-12-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_alter_colorstock_codigo_referencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorstock',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Peso en Kilogramos (Kg)', max_digits=5),
        ),
    ]
