# Generated by Django 4.2.6 on 2024-04-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_colorstock_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstock',
            name='codigo_articulo',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
