# Generated by Django 4.2.6 on 2025-03-17 17:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_alter_colorstock_codigo_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorstock',
            name='codigo_articulo',
        ),
        migrations.AlterField(
            model_name='colorstock',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
