# Generated by Django 4.2.6 on 2025-03-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_remove_colorstock_codigo_articulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='desactivado',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
