# Generated by Django 4.2.6 on 2024-05-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ciudad', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('contacto', models.CharField(max_length=100, null=True, verbose_name='Contacto')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, null=True, verbose_name='Teléfono')),
                ('numeroFactura', models.CharField(max_length=20, null=True, verbose_name='Numero de Factura')),
            ],
        ),
    ]
