# Generated by Django 4.2.6 on 2024-06-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajero', models.CharField(max_length=20)),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('valor_apertura', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='abierta', max_length=20)),
            ],
        ),
    ]
