# Generated by Django 4.2.6 on 2024-06-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0004_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='usuario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
