# Generated by Django 4.2.6 on 2024-12-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0008_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='efectivo_contado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caja',
            name='efectivo_servicios',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caja',
            name='efectivo_ventas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caja',
            name='total_efectivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caja',
            name='total_general',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caja',
            name='total_servicios',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caja',
            name='total_ventas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
