# Generated by Django 4.2.6 on 2025-03-29 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_producto_desactivado'),
        ('operacion', '0010_remove_caja_total_efectivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numeroFactura', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='numeroFactura',
        ),
        migrations.CreateModel(
            name='ProductosActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=10)),
                ('id_actualizacionstock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.actualizacionstock')),
                ('id_colorstock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.colorstock')),
            ],
        ),
        migrations.AddField(
            model_name='actualizacionstock',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.proveedor'),
        ),
    ]
