# Generated by Django 4.2.6 on 2025-03-29 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_producto_desactivado'),
        ('operacion', '0011_actualizacionstock_remove_proveedor_numerofactura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosactualizacion',
            name='id_actualizacionstock',
        ),
        migrations.RemoveField(
            model_name='productosactualizacion',
            name='id_colorstock',
        ),
        migrations.AddField(
            model_name='actualizacionstock',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productosactualizacion',
            name='actualizacionstock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.actualizacionstock'),
        ),
        migrations.AddField(
            model_name='productosactualizacion',
            name='colorstock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.colorstock'),
        ),
    ]
