# Generated by Django 4.2.6 on 2025-03-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0012_remove_productosactualizacion_id_actualizacionstock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosactualizacion',
            name='cantidad',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
