# Generated by Django 4.2.6 on 2025-03-30 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_producto_desactivado'),
        ('operacion', '0013_alter_productosactualizacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosactualizacion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
