# Generated by Django 4.2.6 on 2025-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0014_productosactualizacion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosactualizacion',
            name='precio_actualizado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
