# Generated by Django 4.2.6 on 2025-04-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0016_alter_actualizacionstock_numerofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionstock',
            name='numeroFactura',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
