# Generated by Django 4.2.6 on 2025-04-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0017_alter_actualizacionstock_numerofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionstock',
            name='numeroFactura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
