# Generated by Django 4.2.6 on 2025-07-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0018_alter_actualizacionstock_numerofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(max_length=200, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=200, null=True, verbose_name='Dirección'),
        ),
    ]
